name: Publish Docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    if: github.repository == 'visprex/visprex.github.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          CUSTOM_DOMAIN: docs.visprex.com
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt
